name: TypeScript

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.ts'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Install dependencies
          run: |
            npm i
            npm i -g typescript
        - name: Compile
          run: tsc
        - name: Apply changes
          run: |
            git config --global user.name "Github Actions"
            git config --global user.email "actions@github.com"
            git add .
            git commit -m "TypeScript auto-compile"
            git push
