name: TypeScript

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.ts'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20

        - name: Install dependencies
          run: npm i

        - name: Compile
          run: tsc

        - name: Apply changes
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            if git diff --cached --exit-code; then
              git commit -m "TypeScript auto-compile"
              git push
            fi
          continue-on-error: true